apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-distributed-backend
spec:
  template:
    spec:
      containers:
        - name: cicada-distributed-backend
          image: cicadatesting/cicada-distributed-backend:local
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: cicada-distributed-backend
spec:
  ports:
  - port: 8283
    protocol: TCP
    targetPort: 8283
    nodePort: 30083
  type: NodePort
