name: Pre-Release-PyPi
on:
  release:
    types:
      - prereleased
jobs:
  push-to-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::939879343571:role/github
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade build wheel
          python3 -m pip install --user --upgrade twine
      - name: Package
        run: |
          make build-bin
          make package
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
