name: Pre-Release-Docker
on:
  workflow_run:
    workflows:
      - Pre-Release-PyPi
    branches:
      - main
    types:
      - completed
jobs:
  push-base-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/base-image.dev-b.dockerfile
          platforms: linux/amd64
          push: true
          tags: cicadatesting/cicada-distributed-base-image:${{ github.sha }},cicadatesting/cicada-distributed-base-image:pre-release
  push-manager:
    runs-on: ubuntu-latest
    needs: push-base-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/manager.dev-b.dockerfile
          platforms: linux/amd64
          push: true
          tags: cicadatesting/cicada-distributed-manager:${{ github.sha }},cicadatesting/cicada-distributed-manager:pre-release
  smoke-test:
    runs-on: ubuntu-latest
    needs: push-manager
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: smoke-test
        run: |
          make install-dev-remote
          mkdir smoke-test
          ENV=dev cicada-distributed --debug init ./smoke-test
          cd smoke-test
          ls
          ENV=dev cicada-distributed --debug start-cluster
          docker ps
          ENV=dev cicada-distributed --debug run
          ENV=dev cicada-distributed --debug stop-cluster
          docker ps
