name: Code Check
on:
  push:
    branches-ignore:
      - dev
      - main
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit mypy flake8 types-protobuf
          make install-local
      - name: Securtity
        run: |
          bandit src/cicadad -r -c bandit.yaml
      - name: Types
        run: |
          mypy src/cicadad
      - name: Lint
        run: |
          flake8 src/cicadad
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          make install-local
      - name: Unit Test
        run: |
          pytest src/tests
  unit-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - run: |
          cd backend
          go test -v ./...
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - name: prepare-cicadad
        run: |
          make install-local
      - name: run-integration-test
        run: |
          cd integration-test
          ls
          ENV=local cicada-distributed --debug run -t run --log-path logs --no-exit-unsuccessful --test-timeout 30
          ls
          ls logs
  docker-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: prepare-cicadad
        run: |
          make install-local
          make build-base-local
      - name: build-backend-local
        run: |
          cd backend
          make build-local
      - name: run-smoke-test
        run: |
          mkdir smoke-test
          ENV=local cicada-distributed --debug init ./smoke-test
          cd smoke-test
          ls
          ENV=local cicada-distributed --debug start-cluster
          docker ps
          ENV=local cicada-distributed --debug run --mode=DOCKER
          ENV=local cicada-distributed --debug stop-cluster
          docker ps
  kube-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: prepare-cicadad
        run: |
          make install-local
          make build-base-local
      - name: build-backend-local
        run: |
          cd backend
          make build-local
      - name: setup-cluster
        run: |
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
          make setup-cluster
          make import-images-local
          make install-kube
          docker ps
          kubectl get pods
        # NOTE: may need to wait for pods
      - name: run-smoke-test
        run: |
          mkdir smoke-test
          ENV=local cicada-distributed --debug init ./smoke-test
          cd smoke-test
          ls
          docker build -t cicadatesting/smoke-test:local .
          k3d image import cicadatesting/smoke-test:local
          ENV=local cicada-distributed --debug run --mode=KUBE --image=cicadatesting/smoke-test:local
          cd ..
          make uninstall-kube
          make teardown-cluster
          docker ps
