name: Release-Docker
on:
  workflow_run:
    workflows:
      - Release-PyPi
    types:
      - completed
env:
  cicadaVersion: "1.3.0"
jobs:
  push-base-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/base-image.dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            CICADA_VERSION=${{ env.cicadaVersion }}
          tags: cicadatesting/cicada-distributed-base-image:${{ github.sha }},cicadatesting/cicada-distributed-base-image:${{ env.cicadaVersion }},cicadatesting/cicada-distributed-base-image:latest
  push-container-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: container-service
          file: container-service/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cicadatesting/cicada-distributed-container-service:${{ github.sha }},cicadatesting/cicada-distributed-container-service:${{ env.cicadaVersion }},cicadatesting/cicada-distributed-container-service:latest
  push-datastore-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: datastore-client
          file: datastore-client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cicadatesting/cicada-distributed-datastore-client:${{ github.sha }},cicadatesting/cicada-distributed-datastore-client:${{ env.cicadaVersion }},cicadatesting/cicada-distributed-datastore-client:latest
  smoke-test:
    runs-on: ubuntu-latest
    needs:
      - push-base-image
      - push-container-service
      - push-datastore-client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: smoke-test
        run: |
          pip install cicadad==${{ env.cicadaVersion }}
          mkdir smoke-test
          cicada-distributed --debug init ./smoke-test
          cd smoke-test
          ls
          cicada-distributed --debug start-cluster
          docker ps
          cicada-distributed --debug run
          cicada-distributed --debug stop-cluster
          docker ps
