name: Release-PyPi
on: push
  # release:
  #   types:
  #     - released
jobs:
  push-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade build wheel
          python3 -m pip install --user --upgrade twine
      - name: Package
        run: |
          make package
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://pypi.python.org/
